# ---------------------------------------------------------------#
# __name__ = "Image Stitching Tool EE610 course project"
# __author__ = "Shyama P"
# __author__ = "Shubham Singhania"
# __author__ = "Sona Jose"
# __version__ = "1.0"
# __status__ = "Development"
# ---------------------------------------------------------------#

# This code was generated using QT4 Desginer
# Only few modifications were done on the code

# PyQt4 libraries are used for GUI
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class ImageStitching_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sticthButton = QtGui.QPushButton(self.centralwidget)
        self.sticthButton.setObjectName(_fromUtf8("sticthButton"))
        self.gridLayout.addWidget(self.sticthButton, 1, 2, 1, 1)
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout.addWidget(self.saveButton, 1, 1, 1, 1)
        self.openImageLeftButton = QtGui.QPushButton(self.centralwidget)
        self.openImageLeftButton.setObjectName(_fromUtf8("openImageLeftButton"))
        self.gridLayout.addWidget(self.openImageLeftButton, 1, 0, 1, 1)
        self.openImageRightButton = QtGui.QPushButton(self.centralwidget)
        self.openImageRightButton.setObjectName(_fromUtf8("openImageRightButton"))
        self.gridLayout.addWidget(self.openImageRightButton, 2, 0, 1, 1)
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout.addWidget(self.resetButton, 2, 1, 1, 1)
        self.viewSIFTButton = QtGui.QPushButton(self.centralwidget)
        self.viewSIFTButton.setObjectName(_fromUtf8("viewSIFTButton"))
        self.gridLayout.addWidget(self.viewSIFTButton, 2, 2, 1, 1)
        self.toggleButton = QtGui.QPushButton(self.centralwidget)
        self.toggleButton.setObjectName(_fromUtf8("toggleButton"))
        self.gridLayout.addWidget(self.toggleButton, 1, 3, 1, 1)
        self.label1 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setText(_fromUtf8(""))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 3, 0, 1, 1)
        self.label2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setText(_fromUtf8(""))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 3, 1, 1, 1)
        self.label3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setText(_fromUtf8(""))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 3, 2, 1, 1)
        self.label4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setText(_fromUtf8(""))
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 3, 3, 1, 1)
        # self.viewSIFT2Button = QtGui.QPushButton(self.centralwidget)
        # self.viewSIFT2Button.setObjectName(_fromUtf8("viewSIFT2Button"))
        # self.gridLayout.addWidget(self.viewSIFT2Button, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.imageLeftDisplay = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageLeftDisplay.sizePolicy().hasHeightForWidth())
        self.imageLeftDisplay.setSizePolicy(sizePolicy)
        self.imageLeftDisplay.setText(_fromUtf8(""))
        self.imageLeftDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLeftDisplay.setObjectName(_fromUtf8("imageLeftDisplay"))
        self.horizontalLayout.addWidget(self.imageLeftDisplay)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.imageRightDisplay = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageRightDisplay.sizePolicy().hasHeightForWidth())
        self.imageRightDisplay.setSizePolicy(sizePolicy)
        self.imageRightDisplay.setText(_fromUtf8(""))
        self.imageRightDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.imageRightDisplay.setObjectName(_fromUtf8("imageRightDisplay"))
        self.horizontalLayout.addWidget(self.imageRightDisplay)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.outputImageDisplay = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputImageDisplay.sizePolicy().hasHeightForWidth())
        self.outputImageDisplay.setSizePolicy(sizePolicy)
        self.outputImageDisplay.setText(_fromUtf8(""))
        self.outputImageDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageDisplay.setObjectName(_fromUtf8("outputImageDisplay"))
        self.verticalLayout.addWidget(self.outputImageDisplay)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Stitching Tool", None))
        self.sticthButton.setText(_translate("MainWindow", "Stitch images", None))
        self.saveButton.setText(_translate("MainWindow", "Save output image", None))
        self.openImageLeftButton.setText(_translate("MainWindow", "Choose input left", None))
        self.openImageRightButton.setText(_translate("MainWindow", "Choose input right", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.viewSIFTButton.setText(_translate("MainWindow", "View SIFT keypoints", None))
        self.toggleButton.setText(_translate("MainWindow", "Toggle left and right images", None))
        # self.viewSIFT2Button.setText(_translate("MainWindow", "View SIFT keypoints (2)", None))
        self.label_5.setText(_translate("MainWindow", "Input image - left", None))
        self.label_4.setText(_translate("MainWindow", "Input image - right", None))
        self.label_6.setText(_translate("MainWindow", "Output image", None))
